### ISSUE TITLE
Different fingerprints on same browser

### ISSUE THREAD

**Issue by pramodkumardamam73** [Valve/fingerprintjs#39] opened 2016-04-09 11:00 UTC
Hi,

I have been using your library on one of my project. Everything is working really great. I just came across one bug that it is generating different fingerprints on same browser but different tabs but different hosts. I hope you understand it. It would be great if you can give a solution for it

**Comment by Valve** [comment] 2016-04-09 14:43
Please let me know how to reproduce the issue, I cannot do it

**Comment by pramodkumardamam73** [comment] 2016-04-09 15:21
I am not sure it happens again. But if it's happening on my browser. Any how I can explain what I have done. I have a page where I were fingerprint and store the browser information. I have another scenario where my customers get JavaScript file from my site. I have written the JavaScript file in such a manner it takes the fingerprint and sends the browser info to my servers. So now it is working fine. It is giving same fingerprint in both above mentioned methods. But on one of my pc it is giving different fingerprints on sand browser. 

Is there any chance that fingerprint will get changed on the basis of host, content of page??

**Comment by Valve** [comment] 2016-04-11 14:09
No there is no chance of that, it has no access to host and does not depend on the page content.
Please compare the fingerprinting components that are generated in both cases and find the one which is different. This way I will be able to diagnose the issue further

**Comment by Valve** [comment] 2016-04-11 18:56
I'll close the issue for now. Please feel free to reopen with a detailed instruction of how to reproduce it.
Currently the issue cannot be reproduced following your description.

**Closed by Valve** 2016-04-11 18:56 UTC

**Comment by sundarseswaran** [comment] 2016-08-15 07:10
@Valve - fingerprintjs2 is really awesome started using this for one of our projects.  kudos to the maintainers!!

Had few inconsistencies with the fingerprint retrieved for the same website. The fingerprint was obtained within the angularjs service was different from the fingerprint calculate when module was loaded with in `<script>` tags on a plain html. I added the below exclusions to receive a consistent fingerprint.

`
{excludeJsFonts: true, excludeFlashFonts: true, excludeAvailableScreenResolution: true}
`


I have tried to explain the current issue I'm facing, in the below screenshots. It is very similar to the issue you guys have discussed above.  Same code when executed in production provides a fingerprint that is different from the fingerprint calculated in a lower environment with different domain name.  I was trying to understand the root cause for this issue and stumbled on a weird problem where -- **window.devicePixelRatio** -- one of the parameter for fingerprint calculation returns an unexpected value even from the browser console. 

I am running a MacBook Pro (Retina, 15-inch, Mid 2014),  the value for devicePixelRation should be "2".. whereas only under my production domain name I get a value of "1.7999999523162842". I am not sure if the fingerprintjs library can do anything about this. Of course, the problem can be addressed changing the _getPixelRatio()_ function as below. But, I am still struggling to understand the root cause for this issue. Could be a Chrome browser issue, I don't see this issue in other browsers.

`
    getPixelRatio: function() {
      return  Math.round(window.devicePixelRatio) || "";
    },
`

Please take a look at these screenshots.  Let me know if there is any further information that can help you unravel the mystery here.

<img width="1072" alt="screen shot 2016-08-15 at 2 38 53 am" src="https://cloud.githubusercontent.com/assets/4308836/17657941/5e9b1dfe-6295-11e6-9baa-618b5f16d701.png">

<img width="438" alt="screen shot 2016-08-15 at 2 42 54 am" src="https://cloud.githubusercontent.com/assets/4308836/17657942/6893449e-6295-11e6-849b-8e53a8d32b4e.png">

**Comment by Valve** [comment] 2016-08-15 08:29
@sundarseswaran, Thank you for using the library!

In your case, it may be that you have zoomed out (made everything smaller) for one of your websites where you're having this weird 1.79999 pixel ratio. Please verify the zoom level and let me know if it can be reset with `Ctrl+0` and if it fixes the issue.
As a side note, zooming the webpage is really hard for FP - it's one of the hardest bugs for the library that I know of, I currently have no working solution for this.

**Comment by sundarseswaran** [comment] 2016-08-15 14:46
@Valve -- thanks a lot for your quick response.  this is awesome! I never knew this before.

Again, its a great library!!
