### ISSUE TITLE
Chrome issue

### ISSUE THREAD

**Issue by drstyv** [Valve/fingerprintjs#29] opened 2015-04-22 09:49 UTC
Hello! i am using your browser fingerprint system and it has been working really great for some time!
However a couple of days ago some of my users have had issues that their browser fingerprints where the same when using Google Chrome!

has Google Chrome made any updates to make it harder for browser fingerprint to get a unique id?

**Comment by Valve** [comment] 2015-04-22 10:41
Hi @drstyv,

Thank you for using the library.

To look into it, more details are needed.
I'm currently on chrome and my FP is 3635934679

Please let me know the OS and chrome version you're having issues with.

Thanks

**Comment by jordii** [comment] 2015-04-22 10:44
Hi, i'm seeing the same issue with the latest chrome version.

I have several false positives with these user agents:

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36 

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

Everything seems to be related with the release of the chrome 42 one week ago.

**Comment by Valve** [comment] 2015-04-22 10:45
@jordii thanks, my chrome version is exactly 42.0.2311.90 (64-bit)
I'm looking into it now.

**Comment by Valve** [comment] 2015-04-22 10:54
@jordii, you have two different UserAgent strings in your example. Are the fingerprints different for these two browsers?
I've just looked into FP generation on my laptop (Chrome 42 + latest OSX), everything seems normal:
"["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36","en-US",24,"1200x1920",-180,true,true,true,"undefined","function",null,"MacIntel","1","Widevine Content Decryption Module::Enables Widevine licenses for playback of HTML audio/video content. (version: 1.4.7.796)::application/x-ppapi-widevine-cdm~;Native Client::::application/x-nacl~,application/x-pnacl~,text/html~;Chrome PDF Viewer::::application/pdf~pdf;Shockwave Flash::Shockwave Flash 17.0 r0::application/x-shockwave-flash~swf,application/futuresplash~spl;Chrome Remote Desktop Viewer::This plugin allows you to securely access other computers that have been shared with you. To use this plugin you must first install the <a href=\"https://chrome.google.com/remotedesktop\">Chrome Remote Desktop</a> webapp.::application/vnd.chromium.remoting-viewer~;Chrome PDF Viewer::Portable Document Format::application/x-google-chrome-pdf~pdf","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAYtklEQ…ypGJQESIDCYg+QAAkoQ4DCUqZUDEoCJEBhsQdIgASUIfB//dQeHsm1b7QAAAAASUVORK5CYII="]"

**Comment by drstyv** [comment] 2015-04-22 11:03
@Valve i am not a developer, i just use this great product on my website(browser fingerprint).
But i can tell you my website has over 50.000 unique visitors per day and this has been working great without any issues until a week ago i think.

It seems that quite a few Google Chrome users now get same browser fingerprint.

**Comment by jordii** [comment] 2015-04-22 11:05
We have a lot of traffic, and we saw the increase in the matches since 18th april.

When i test on my computer or a colleague (Chrome 42 + latest OSX) we can't see any problems. But when i look into the database (where we store the user agents, the fingerprint code and more data), i have several matches from users with different ips (From different countries like BR and MX), we called some of them and they are different people.
The only thing in common it's the user_agent, i posted two user_agents because that's the two user agents with most of the matches. (Each one separatedly)

**Comment by Valve** [comment] 2015-04-22 11:07
@drstyv , @jordii , got it, I'll test it on windows with the latest chrome and will look into my own database too. Please add any information to help me debug the issue, it'd be very helpful

**Comment by drstyv** [comment] 2015-04-22 13:37
@Valve dont know if this helps but i am running these options on the fingerprint:

var fpid = new Fingerprint({canvas: true,ie_activex: true}).get();

**Comment by jordii** [comment] 2015-04-22 14:35
@Valve Ok, i just logged the keys value i got in the fp, it's here:
http://pastebin.com/mSjLtDwJ
i search the user and i have a lot of matches since 18th april (like 1000 all from brazilian ips)

If it helps too, I'm calling the same way @drstyv  does.

**Comment by Valve** [comment] 2015-04-22 16:04
@jordii are the above keys from the invalid (common) FP or just from your browser?

**Comment by jordii** [comment] 2015-04-22 16:05
@Valve from the invalid one

**Comment by Valve** [comment] 2015-04-23 09:47
@jordii @drstyv I've found the reason: https://threatpost.com/google-shuts-off-npapi-in-chrome/112295

Chrome disabled NPAPI plugins in version 42

**Comment by drstyv** [comment] 2015-04-23 09:51
@Valve any way you can do anything to improve the Google Chrome Fingerprint?

**Comment by Valve** [comment] 2015-04-23 09:52
If I enable npapi in chrome flags and restart Chrome, the plugin string will become:

`
"Widevine Content Decryption Module::Enables Widevine licenses for playback of HTML audio/video content. (version: 1.4.7.796)::application/x-ppapi-widevine-cdm~;Native Client::::application/x-nacl~,application/x-pnacl~,text/html~;Chrome PDF Viewer::::application/pdf~pdf;Shockwave Flash::Shockwave Flash 17.0 r0::application/x-shockwave-flash~swf,application/futuresplash~spl;Chrome Remote Desktop Viewer::This plugin allows you to securely access other computers that have been shared with you. To use this plugin you must first install the <a href="https://chrome.google.com/remotedesktop">Chrome Remote Desktop</a> webapp.::application/vnd.chromium.remoting-viewer~;Chrome PDF Viewer::Portable Document Format::application/x-google-chrome-pdf~pdf;Default Browser Helper::Provides information about the default web browser::application/apple-default-browser~;Google Talk Plugin::Version 5.41.0.0::application/googletalk~googletalk;Java Applet Plug-in::Displays Java applet content, or a placeholder if Java is not installed.::application/x-java-applet;javafx=8.0.31~,application/x-java-applet;version=1.4~,application/x-java-applet;version=1.2.1~,application/x-java-applet;version=1.2.2~,application/x-java-applet;version=1.3~,application/x-java-applet;version=1.8~,application/x-java-vm~,application/x-java-applet;version=1.1.1~,application/x-java-applet;version=1.2~,application/x-java-applet;version=1.7~,application/x-java-applet;version=1.4.1~,application/x-java-applet;version=1.1.2~,application/x-java-applet~,application/x-java-applet;version=1.1~,application/x-java-applet;version=1.1.3~,application/x-java-applet;version=1.6~,application/x-java-applet;version=1.4.2~,application/x-java-applet;deploy=11.31.2~,application/x-java-applet;version=1.3.1~,application/x-java-applet;jpi-version=1.8.0_31~,application/x-java-applet;version=1.5~;Google Talk Plugin Video Renderer::Version 5.41.0.0::application/o1d~o1d"
`

**Comment by Valve** [comment] 2015-04-23 09:54
So, the only advice I can give is to upgrade to fingerprintjs2, it has more FP sources (fonts/webgl) and more will be added over time. I don't know if anything can be done here with Chrome and 1st version of FP

**Comment by drstyv** [comment] 2015-04-23 10:00
@Valve Is the fingerprintjs2 good enough now to start using over fingerprintjs1 ?

**Comment by Valve** [comment] 2015-04-23 10:09
@drstyv I don't think so, because nobody has started using it seriously (yet), I'll be working on it in the upcoming weeks. But currently it has more FP sources than version 1. As for stability - it's not well tested yet.

**Comment by drstyv** [comment] 2015-04-23 10:21
@Valve Do you have an estimate when it will be tested and ready?

**Comment by Valve** [comment] 2015-04-23 10:34
@drstyv, I don't, I'm working on it alone and I don't have much spare time

**Comment by drstyv** [comment] 2015-04-23 10:35
@Valve ok thanks for the update, i will be looking forward to testing the new Fingerprintjs2 when it is ready!

**Comment by lucasas** [comment] 2015-10-15 17:56
@Valve do you have any idea when version 2 will be released? Thanks for the great job.

**Comment by Valve** [comment] 2015-10-15 18:27
@lucasas . We've been having FP2 on prod for several months, no issues, so you can start using it.

The only reason I'm not releasing v 1.0 (yet) is the hard to fix FF behavior - it's very slow on FF on Android. The reason being the font detection with JS. I will fix it this month (I'll try very hard at least). By default, only like 50 most common fonts will be detected, and about 450 less common will be detected if passed a special flag. This should keep the font entropy, but be faster for most people.

If you're OK with lib being slow on FF+Android (500ms .. 5s depending on hardware), you can start using it in prod now. If you want a faster version, then you can either wait while I muster courage to implement the FF improvements or.. submit a PR to help me there.

**Comment by Valve** [comment] 2015-11-13 12:27
@lucasas I've pushed v.1.0-rc1 of FP2. Please have a look at it. I plan to make it v.1.0 release in a week or so if it will have no issues on prod.

**Comment by Valve** [comment] 2016-04-11 18:55
Since this is not a bug, but a fundamental deficiency of the library, I'll close the ticket. Issues like these should be discussed and solved on the FingerprintJS-2

**Closed by Valve** 2016-04-11 18:55 UTC
